
project_id = "tappaygo-platform"
[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
[db]
port = 54322
[studio]
port = 54323
[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326
[storage]
port = 54328
[auth]
port = 54327
[realtime]
port = 54329
[functions.generate-agent-proposals]
verify_jwt = true
[functions.monitor-agent-proposals]
verify_jwt = true
