
project_id = "utraomhphgnnrpyfwwla"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[functions]
[functions.request-api-access]
verify_jwt = true
